package handler

import (
	"time"

	"github.com/gin-gonic/gin"
	"github.com/redis/go-redis/v9"
	swaggerfiles "github.com/swaggo/files"
	ginswagger "github.com/swaggo/gin-swagger"

	// Generated by `swag init`; blank-imported so the spec registers itself.
	_ "golang-gin/docs"
	"golang-gin/internal/pkg/oauth"
	"golang-gin/internal/pkg/password"
	"golang-gin/internal/pkg/session"
	"golang-gin/internal/repository/mysql"
	"golang-gin/internal/service"
)

// Config carries what the wiring needs from outside. It exists so tests can
// point the OAuth client at an httptest.Server instead of the real providers.
type Config struct {
	KakaoBaseURL string
	NaverBaseURL string

	// Redis backs the session store. Login is unavailable without it.
	Redis         redis.UniversalClient
	SessionSecret []byte
	SessionTTL    time.Duration
}

// NewEngine wires the whole application and returns the router.
//
// Assembly lives here rather than in main so integration tests build the
// engine through the exact same path production does. db is a mysql.DB, so a
// test can pass a *sql.Tx it rolls back afterwards.
func NewEngine(db mysql.DB, cfg Config) *gin.Engine {
	txRunner := mysql.NewTxRunner(db)
	customerRepo := mysql.NewCustomerRepository(db)
	passwordRepo := mysql.NewCustomerPasswordRepository(db)
	socialRepo := mysql.NewCustomerSocialRepository(db)

	var opts []oauth.Option
	if cfg.KakaoBaseURL != "" {
		opts = append(opts, oauth.WithKakaoBaseURL(cfg.KakaoBaseURL))
	}
	if cfg.NaverBaseURL != "" {
		opts = append(opts, oauth.WithNaverBaseURL(cfg.NaverBaseURL))
	}
	oauthClient := oauth.NewClient(opts...)

	hasher := password.NewHasher(password.DefaultParams())
	sessions := session.NewStore(cfg.Redis, cfg.SessionSecret, cfg.SessionTTL)
	customerService := service.NewCustomerService(txRunner, customerRepo, passwordRepo, socialRepo, hasher, oauthClient, sessions)

	authHandler := NewAuthHandler(customerService)

	r := gin.New()
	r.Use(gin.Recovery())

	r.GET("/", Health)
	r.GET("/health", Health)
	r.GET("/swagger/*any", ginswagger.WrapHandler(swaggerfiles.Handler))

	auth := r.Group("/auth")
	auth.POST("/signup", authHandler.SignUp)
	auth.POST("/login", authHandler.Login)

	return r
}
