// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countCustomersByStatus = `-- name: CountCustomersByStatus :one
SELECT COUNT(*)
FROM customer
WHERE status = ?
`

func (q *Queries) CountCustomersByStatus(ctx context.Context, status uint8) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCustomersByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :execresult
INSERT INTO customer (email, name, status)
VALUES (?, ?, ?)
`

type CreateCustomerParams struct {
	Email  string
	Name   string
	Status uint8
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCustomer, arg.Email, arg.Name, arg.Status)
}

const deleteCustomer = `-- name: DeleteCustomer :execresult
DELETE FROM customer
WHERE id = ?
`

func (q *Queries) DeleteCustomer(ctx context.Context, id uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCustomer, id)
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, email, name, status, created_at, updated_at
FROM customer
WHERE id = ?
`

func (q *Queries) GetCustomer(ctx context.Context, id uint64) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, email, name, status, created_at, updated_at
FROM customer
WHERE email = ?
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByMedia = `-- name: GetCustomerByMedia :one
SELECT c.id, c.email, c.name, c.status, c.created_at, c.updated_at
FROM customer c
JOIN customer_social s ON s.customer_id = c.id
WHERE s.media_name = ? AND s.media_id = ?
`

type GetCustomerByMediaParams struct {
	MediaName string
	MediaID   string
}

func (q *Queries) GetCustomerByMedia(ctx context.Context, arg GetCustomerByMediaParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByMedia, arg.MediaName, arg.MediaID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerWithPasswordByEmail = `-- name: GetCustomerWithPasswordByEmail :one
SELECT c.id, c.email, c.name, c.status, c.created_at, c.updated_at, p.password_hash
FROM customer c
JOIN customer_password p ON p.customer_id = c.id
WHERE c.email = ?
`

type GetCustomerWithPasswordByEmailRow struct {
	ID           uint64
	Email        string
	Name         string
	Status       uint8
	CreatedAt    time.Time
	UpdatedAt    time.Time
	PasswordHash string
}

func (q *Queries) GetCustomerWithPasswordByEmail(ctx context.Context, email string) (GetCustomerWithPasswordByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerWithPasswordByEmail, email)
	var i GetCustomerWithPasswordByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const listCustomersByStatus = `-- name: ListCustomersByStatus :many
SELECT id, email, name, status, created_at, updated_at
FROM customer
WHERE status = ?
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListCustomersByStatusParams struct {
	Status uint8
	Limit  int32
	Offset int32
}

func (q *Queries) ListCustomersByStatus(ctx context.Context, arg ListCustomersByStatusParams) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerName = `-- name: UpdateCustomerName :execresult
UPDATE customer
SET name = ?
WHERE id = ?
`

type UpdateCustomerNameParams struct {
	Name string
	ID   uint64
}

func (q *Queries) UpdateCustomerName(ctx context.Context, arg UpdateCustomerNameParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCustomerName, arg.Name, arg.ID)
}

const updateCustomerProfile = `-- name: UpdateCustomerProfile :execresult
UPDATE customer
SET name = ?, email = ?
WHERE id = ?
`

type UpdateCustomerProfileParams struct {
	Name  string
	Email string
	ID    uint64
}

func (q *Queries) UpdateCustomerProfile(ctx context.Context, arg UpdateCustomerProfileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCustomerProfile, arg.Name, arg.Email, arg.ID)
}

const updateCustomerStatus = `-- name: UpdateCustomerStatus :execresult
UPDATE customer
SET status = ?
WHERE id = ?
`

type UpdateCustomerStatusParams struct {
	Status uint8
	ID     uint64
}

func (q *Queries) UpdateCustomerStatus(ctx context.Context, arg UpdateCustomerStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCustomerStatus, arg.Status, arg.ID)
}
