// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_password.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createCustomerPassword = `-- name: CreateCustomerPassword :execresult
INSERT INTO customer_password (customer_id, password_hash)
VALUES (?, ?)
`

type CreateCustomerPasswordParams struct {
	CustomerID   uint64
	PasswordHash string
}

func (q *Queries) CreateCustomerPassword(ctx context.Context, arg CreateCustomerPasswordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCustomerPassword, arg.CustomerID, arg.PasswordHash)
}

const deleteCustomerPassword = `-- name: DeleteCustomerPassword :execresult
DELETE FROM customer_password
WHERE customer_id = ?
`

func (q *Queries) DeleteCustomerPassword(ctx context.Context, customerID uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCustomerPassword, customerID)
}

const getCustomerPassword = `-- name: GetCustomerPassword :one
SELECT customer_id, password_hash, created_at, updated_at
FROM customer_password
WHERE customer_id = ?
`

func (q *Queries) GetCustomerPassword(ctx context.Context, customerID uint64) (CustomerPassword, error) {
	row := q.db.QueryRowContext(ctx, getCustomerPassword, customerID)
	var i CustomerPassword
	err := row.Scan(
		&i.CustomerID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomerPassword = `-- name: UpdateCustomerPassword :execresult
UPDATE customer_password
SET password_hash = ?
WHERE customer_id = ?
`

type UpdateCustomerPasswordParams struct {
	PasswordHash string
	CustomerID   uint64
}

func (q *Queries) UpdateCustomerPassword(ctx context.Context, arg UpdateCustomerPasswordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCustomerPassword, arg.PasswordHash, arg.CustomerID)
}
