// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_social.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createCustomerSocial = `-- name: CreateCustomerSocial :execresult
INSERT INTO customer_social (customer_id, media_name, media_id)
VALUES (?, ?, ?)
`

type CreateCustomerSocialParams struct {
	CustomerID uint64
	MediaName  string
	MediaID    string
}

func (q *Queries) CreateCustomerSocial(ctx context.Context, arg CreateCustomerSocialParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCustomerSocial, arg.CustomerID, arg.MediaName, arg.MediaID)
}

const deleteCustomerSocial = `-- name: DeleteCustomerSocial :execresult
DELETE FROM customer_social
WHERE id = ?
`

func (q *Queries) DeleteCustomerSocial(ctx context.Context, id uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCustomerSocial, id)
}

const deleteCustomerSocialsByCustomer = `-- name: DeleteCustomerSocialsByCustomer :execresult
DELETE FROM customer_social
WHERE customer_id = ?
`

func (q *Queries) DeleteCustomerSocialsByCustomer(ctx context.Context, customerID uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteCustomerSocialsByCustomer, customerID)
}

const getCustomerSocial = `-- name: GetCustomerSocial :one
SELECT id, customer_id, media_name, media_id, created_at, updated_at
FROM customer_social
WHERE id = ?
`

func (q *Queries) GetCustomerSocial(ctx context.Context, id uint64) (CustomerSocial, error) {
	row := q.db.QueryRowContext(ctx, getCustomerSocial, id)
	var i CustomerSocial
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.MediaName,
		&i.MediaID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerSocialByMedia = `-- name: GetCustomerSocialByMedia :one
SELECT id, customer_id, media_name, media_id, created_at, updated_at
FROM customer_social
WHERE media_name = ? AND media_id = ?
`

type GetCustomerSocialByMediaParams struct {
	MediaName string
	MediaID   string
}

func (q *Queries) GetCustomerSocialByMedia(ctx context.Context, arg GetCustomerSocialByMediaParams) (CustomerSocial, error) {
	row := q.db.QueryRowContext(ctx, getCustomerSocialByMedia, arg.MediaName, arg.MediaID)
	var i CustomerSocial
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.MediaName,
		&i.MediaID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomerSocialsByCustomer = `-- name: ListCustomerSocialsByCustomer :many
SELECT id, customer_id, media_name, media_id, created_at, updated_at
FROM customer_social
WHERE customer_id = ?
ORDER BY id
`

func (q *Queries) ListCustomerSocialsByCustomer(ctx context.Context, customerID uint64) ([]CustomerSocial, error) {
	rows, err := q.db.QueryContext(ctx, listCustomerSocialsByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerSocial{}
	for rows.Next() {
		var i CustomerSocial
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.MediaName,
			&i.MediaID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerSocialMediaID = `-- name: UpdateCustomerSocialMediaID :execresult
UPDATE customer_social
SET media_id = ?
WHERE id = ?
`

type UpdateCustomerSocialMediaIDParams struct {
	MediaID string
	ID      uint64
}

func (q *Queries) UpdateCustomerSocialMediaID(ctx context.Context, arg UpdateCustomerSocialMediaIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCustomerSocialMediaID, arg.MediaID, arg.ID)
}
