// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"
)

type Customer struct {
	ID    uint64
	Email string
	Name  string
	// 0: deleted, 1: active, 2: inactive
	Status    uint8
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CustomerPassword struct {
	CustomerID uint64
	// Argon2id PHC 인코딩 문자열. 알고리즘과 파라미터가 값 안에 포함된다.
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CustomerSocial struct {
	ID         uint64
	CustomerID uint64
	MediaName  string
	MediaID    string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
